//
// local
//

// GET
// get all contacts
GET http://localhost:8080/contacts

// get contact by id
GET http://localhost:8080/contacts/681fee16bf7e8fcb85af409a


// POST
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Rick",
    "lastName":"Ross",
    "email":"ilikepears@mmg.com",
    "favoriteColor":"gold",
    "birthday":"06/05/73"
}


// PUT 
// update all new properties
PUT http://localhost:8080/contacts/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "firstName":"",
    "lastName":"Wayne",
    "email":"weezyfbaby@ymcmb.com",
    "favoriteColor":"purple",
    "birthday":"06/05/93"
}

// update just one
PUT http://localhost:8080/contacts/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "lastName":"Baby"
}


// DELETE
// this you may have to alter to another id from the collection
DELETE http://localhost:8080/contacts/681ffcbc6332ce3fe196a4f4 HTTP/1.1


//
// production
//

// GET
// get all contacts
GET https://express-server-c7bg.onrender.com/contacts

// get contact by id
GET https://express-server-c7bg.onrender.com/contacts/6816c31651de9aab35415445


// POST
POST https://express-server-c7bg.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Nasir",
    "lastName":"Jones",
    "email":"asdfdsafdsa@mmg.com",
    "favoriteColor":"gold",
    "birthday":"06/05/73"
}


// PUT 
// update all properties
PUT https://express-server-c7bg.onrender.com/contacts/681ffd396332ce3fe196a4f6 HTTP/1.1
content-type: application/json

{
    "firstName":"Tupac",
    "lastName":"Shakur",
    "email":"weezyfbaby@ymcmb.com",
    "favoriteColor":"red",
    "birthday":"06/05/93"
}

// update one or multiple properties
PUT https://express-server-c7bg.onrender.com/contacts/6816c36451de9aab35415447 HTTP/1.1
content-type: application/json

{
    "lastName":"Pan"
}


// DELETE
// this you may have to alter to another id from the collection
DELETE https://express-server-c7bg.onrender.com/contacts/681fec87903dd5d23ce5ca65 HTTP/1.1


// highlight http request (and json body if applicable) then type ctrl + alt + R